version: '3.9'

services:
  backend:
    build:
      context: ./App_Full_Stack  # Ruta a la carpeta del backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./imdb_full_stack  # Ruta a la carpeta del frontend
    ports:
      - "3000:3000"
    command: npm start
    stdin_open: true
    tty: true
    volumes:
      - ./imdb_full_stack:/app  # Ajusta la ruta del volumen según la carpeta del frontend
    depends_on:
      - backend
