# Generated by Django 4.2.7 on 2023-11-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('nconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primaryName', models.CharField(max_length=255)),
                ('birthYear', models.CharField(max_length=10)),
                ('deathYear', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('tconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=10)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('originalTitle', models.CharField(max_length=255)),
                ('isAdult', models.BooleanField(default=False)),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('runtimeMinutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='imdb.actor')),
                ('ordering', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('characters', models.TextField(blank=True, null=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='imdb.pelicula')),
            ],
        ),
    ]
