# Generated by Django 4.2.7 on 2023-11-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='endYear',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
