# Generated by Django 4.2.7 on 2023-11-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_alter_pelicula_endyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='startYear',
            field=models.CharField(max_length=10),
        ),
    ]
