# Generated by Django 4.2.7 on 2023-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_alter_pelicula_startyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='deathYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
