# Generated by Django 4.2.7 on 2023-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_alter_actor_deathyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
